name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy core
        run: rsync -avz --rsync-path='sudo rsync' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/moodle/local/${{ github.event.repository.name }}/
      - name: Deploy client
        run: rsync -avz --rsync-path='sudo rsync' ./client/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/moodle/
      
